src/Entity/Log.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LogRepository")
 */
class Log
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $start;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $end;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $message;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Job", inversedBy="logs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $job;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(?\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(?\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(?string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getJob(): ?Job
    {
        return $this->job;
    }

    public function setJob(?Job $job): self
    {
        $this->job = $job;

        return $this;
    }

    /**
     * Generate duration from start en end time
     *
     * @return float|null The duration in minutes
     */
    public function getDuration(): ?float
    {
        if ($this->getEnd() !== null) {
            $deltaT = $this->getEnd()->format('U') - $this->getStart()->format('U');

            return round($deltaT / 60);
        }

        return null;
    }

    /**
     * Convert duration in human readable time [hh:mm]
     *
     * @return string|null The duration in human readable time
     */
    public function getPrettyDuration(): ?string
    {
        if ($this->getDuration() !== null) {
            return sprintf('%02d:%02d', floor($this->getDuration() / 60), $this->getDuration() % 60);
        }

        return null;
    }

    /**
     * Get the duration color label based on execution time
     *
     * @return string
     */
    public function getDurationColor(): string
    {
        if ($this->getStatus() == 'error') {
            return 'danger';
        }
        if ($this->getDuration() === null) {
            $color = 'secondary';
        } elseif ($this->getDuration() < 30) {
            //green
            $color = 'success';
        } elseif ($this->getDuration() < 60) {
            // ligth blue
            $color = 'info';
        } elseif ($this->getDuration() < 120) {
            //blue
            $color = 'primary';
        } elseif ($this->getDuration() < 240) {
            //orange
            $color = 'warning';
        } else {
            //red
            $color = 'danger';
        }

        return $color;
    }

    public function getDurationIcon(): string
    {
        if ($this->getStatus() == 'error') {
            return '<i class="fa fa-bomb"></i>';
        }

        if ($this->getDuration() === null) {
            $icon = '<i class="fa fa-question-circle"></i>';
        } elseif ($this->getDuration() < 30) {
            //green
            $icon = '<i class="fa fa-check-circle"></i>';
        } elseif ($this->getDuration() < 60) {
            // ligth blue
            $icon = '<i class="fa fa-check-circle"></i>';
        } elseif ($this->getDuration() < 120) {
            //blue
            $icon = '<i class="fa fa-check-circle"></i>';
        } elseif ($this->getDuration() < 240) {
            //orange
            $icon = '<i class="fa fa-check-circle"></i>';
        } else {
            //red
            $icon = '<i class="fa fa-warning"></i>';
        }

        return $icon;
    }

    public function __toString()
    {
        return "Exec. time: " . $this->getPrettyDuration() . " | " .
        "Status: " . $this->getStatus() . " | " .
        "Message: " . $this->getMessage();
    }
}

src/Controller/LogController.php
<?php

namespace App\Controller;

use App\Entity\Job;
use App\Repository\JobRepository;
use App\Repository\LogRepository;
use App\Service\LaunchJobHandler;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LogController extends AbstractController
{
    private $launchJobHandler;

    public function __construct(LaunchJobHandler $launchJobHandler)
    {
        $this->launchJobHandler = $launchJobHandler;
    }

    /**
     * @Route("/", name="log_index", methods={"GET"})
     *
     * @param LogRepository $logRepository
     * @param JobRepository $jobRepository
     *
     * @return Response
     */
    public function homepage(LogRepository $logRepository, JobRepository $jobRepository): Response
    {
        $nbExec = 10;
        $jobs = $jobRepository->findAll();
        /**
         * @var Job[]
         */
        $jobsLogs = [];

        foreach ($jobs as $job) {
            $job->setArrayLogs($logRepository->findLastByJob($job, $nbExec));
            $jobsLogs[$job->getId()] = $job;
        }

        return $this->render('log/index.html.twig', ['jobsLogs' => $jobsLogs, 'nbExec' => $nbExec]);
    }

    /**
     * @Route("/detail/{id}", name="log_detail", methods={"GET"})
     *
     * @param Job           $job
     * @param LogRepository $logRepository
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function detail(Job $job, LogRepository $logRepository)
    {
        return $this->render(
            'log/detail.html.twig',
            [
                'job' => $job,
                'logs' => $logRepository->findAllByJob($job),
            ]
        );
    }

    /**
     * @Route("/run/{id}", name="run_job", methods={"GET"})
     *
     * @param Job $job
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function run(Job $job)
    {
        $this->launchJobHandler->startJob($job);
        $response = new Response();
        $response->setContent('<html><body><h1>Check logs for details </h1></body></html> ');
        $response->setStatusCode(Response::HTTP_OK);

        return $response;
    }
}

templates/log/_sidebar.html.twig
<div class="card">
    <div class="card-header">
        Color/Icon informations
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item list-group-item-success"><i class="fa fa-check-circle"></i> Less than 30 min</li>
        <li class="list-group-item list-group-item-info"><i class="fa fa-check"></i> Less than 1 hour</li>
        <li class="list-group-item list-group-item-primary"><i class="fa fa-check"></i> Less than 2 hours</li>
        <li class="list-group-item list-group-item-warning"><i class="fa fa-check"></i> Less than 4 hours</li>
        <li class="list-group-item list-group-item-danger"><i class="fa fa-warning"></i> More than 4 hours</li>
        <li class="list-group-item list-group-item-secondary"><i class="fa fa-question-circle"></i> No end date</li>
        <li class="list-group-item list-group-item-danger"><i class="fa fa-bomb"></i> Error !!</li>
    </ul>
</div>

templates/log/detail.html.twig
{% extends 'base.html.twig' %}

{% block main %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ path('log_index') }}"><i class="fa fa-chevron-left"></i> Back</a>
            </li>
        </ul>

        <h1 class="h2">Execution details</h1>
        <h2 class="h2">Job: {{ job.name }}</h2>
        <h3 class="h2">Frequency: {{ job.frequency }}</h3>
        <a href="{{ path('run_job', {'id': job.id}) }}">Run</a>
    </div>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Start</th>
                    <th>End</th>
                    <th>Execution time</th>
                    <th>Status</th>
                    <th>Message</th>
                </tr>
            </thead>
            <tbody>
                {% for log in logs %}
                <tr class="table-{{ log.durationColor }} list-group-item-{{ log.durationColor }}">
                    <td>{{ log.id }}</td>
                    <td>{{ log.start|date('d/m/Y H:i:s') }}</td>
                    <td>{{ log.end|date('d/m/Y H:i:s') }}</td>
                    <td>{{ log.prettyDuration }}</td>
                    <td>{{ log.durationIcon|raw }} {{ log.status }}</td>
                    <td>{{ log.message }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
{% block sidebar %}
    {% include 'log/_sidebar.html.twig' %}
{% endblock %}

templates/log/index.html.twig
{% extends 'base.html.twig' %}

{% block main %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Last job execution time</h1>
    </div>

    <div class="table-responsive">
        <table class="table table-hover log">
            <thead>
            <tr>
                <th>Job</th>
                <th>Frequency</th>
                <th colspan="{{ nbExec }}">Last {{ nbExec }} execution</th>
            </tr>
            </thead>
            <tbody>
            {% for job in jobsLogs %}
                <tr>
                    <td class="job_name"><a href="{{ path('log_detail', {'id': job.id}) }}"><i class="fa fa-chevron-circle-right"></i> {{ job.name }}</a></td>
                    <td class="job_frequency">{{ job.frequency }}</td>
                    {% set execution = nbExec %}
                    {% for log in job.arrayLogs %}
                        <td  class="job_execution list-group-item-{{ log.durationColor }}" data-toggle="tooltip"
                             title="Execution time: {{ log.prettyDuration }} | Start time: {{ log.start|date('d/m/Y H:i:s') }} | End time: {{ log.end|date('d/m/Y H:i:s') }}
                        {% if (log.status == "error") %}
                                    | Message : {{ log.message }}
                        {% endif %}
                            ">
                            {{ log.durationIcon|raw }}
                            <br/><span class="job_date">
                                {{ log.start|date('d/m/Y') }}
                                {% if job.frequency == 'hourly' %}
                                <br/>{{ log.start|date('H:i:s') }}
                                {% endif %}
                            </span>
                        </td>
                        {% set execution = execution - 1 %}
                    {% endfor %}
                    {% if execution > 0 %}
                        <td colspan="{{ execution }}"></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
{% block sidebar %}
    {% include 'log/_sidebar.html.twig' %}
{% endblock %}